# Generated by Django 4.1.2 on 2022-10-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='long bio')),
            ],
        ),
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='name')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('short_bio', models.CharField(blank=True, max_length=100, null=True, verbose_name='short bio')),
                ('long_bio', models.TextField(blank=True, null=True, verbose_name='long bio')),
                ('advocate_years_exp', models.IntegerField(blank=True, null=True, verbose_name='advocate years of experience')),
                ('youtube', models.CharField(blank=True, max_length=30, null=True, verbose_name='youtube link')),
                ('twitter', models.CharField(blank=True, max_length=30, null=True, verbose_name='twitter link')),
                ('github', models.CharField(blank=True, max_length=30, null=True, verbose_name='github link')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advocate_user', to='advocate.company')),
            ],
        ),
    ]
